# Generated by Django 3.2 on 2021-05-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_tv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
