# Generated by Django 3.2 on 2021-05-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_alter_mobile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='images',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='product_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='rating',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='reviews',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='specs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
